# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven
on:
  push:
    branches: [ ci_tests ]
  pull_request:
    branches: [ ci_tests ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Setup / Checkout
        uses: actions/checkout@v2
      - name: Setup / Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.3
      - name: Setup / JDK
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Setup / settings.xml
        uses: s4u/maven-settings-action@v2.2.0
        with:
          servers: '[{"id": "default", "username": "${{ secrets.nexus_user }}", "password": "${{ secrets.nexus_password }}"}]'
          mirrors: '[{"id": "default", "name": "default", "mirrorOf": "*", "url": "https://nexus.adito.cloud/repository/maven-public/"}]'
      - name: Setup / Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: images.conceptive.io
          username: ${{ secrets.nexus_user }}
          password: ${{ secrets.nexus_password }}
      - name: Maven / Download Dependencies
        run: mvn -Dmaven.artifact.threads=30 -T 1C -B de.qaware.maven:go-offline-maven-plugin:1.2.8:resolve-dependencies
      - name: Native / Compile
        run: mvn clean package -Pnative -Dquarkus.container-image.build=true
      - name: Native / Integration Test
        run: mvn -Pnative test-compile failsafe:integration-test failsafe:verify
